eclipse-csi/otterdog

CHANGELOG.md
DEPENDENCIES
otterdog/webapp/templates/comment/auto_merge_comment.txt
otterdog/webapp/templates/comment/help_comment.txt
otterdog/webapp/templates/comment/team_membership_comment.txt
otterdog/webapp/templates/comment/validation_comment.txt
otterdog/webapp/webhook/__init__.py
otterdog/webapp/webhook/comment_handlers.py
poetry.lock
pyproject.toml
tests/webapp/webhook/__init__.py
tests/webapp/webhook/test_comment_handlers.py

This fixes #211 .
Changes the existing command to interact in pull requests to use scopes, e.g. `/otterdog validate`

Scoped commands

---

otterdog/webapp/auth/routes.py
otterdog/webapp/db/models.py
otterdog/webapp/db/service.py
otterdog/webapp/home/routes.py
otterdog/webapp/tasks/fetch_config.py
otterdog/webapp/templates/home/index.html
otterdog/webapp/templates/home/page-401.html
otterdog/webapp/templates/home/projects.html
otterdog/webapp/templates/includes/sidebar.html

This PR overhauls the default dashboard view by showing various statistics over all configured projects.

Overhaul dashboard view

---

CHANGELOG.md
otterdog/webapp/config.py
otterdog/webapp/db/service.py
tests/webapp/conftest.py
tests/webapp/db/__init__.py
tests/webapp/db/config/otterdog.json
tests/webapp/db/config/otterdog_modified.json
tests/webapp/db/test_service.py

Fix updating installations with changing github_ids

---

CHANGELOG.md
otterdog/models/__init__.py
otterdog/models/github_organization.py
otterdog/models/repository.py
otterdog/models/secret.py
otterdog/models/webhook.py
otterdog/operations/diff_operation.py
otterdog/operations/local_plan.py

When doing some change to dummy secret values, the local-plan operation did not show these changes which was quite confusing.
This fixes #245 .

Show changes to dummy secret values in local-plan operation

---

CHANGELOG.md
otterdog/cli.py
otterdog/operations/install_app.py
otterdog/providers/github/web.py

feat: add install-app operation

---

.github/workflows/release.yml

While I don't see any issue in current code, it's better practice to place the expression in environment variable before the start of the script.

chore: expand user inputs outside of bash and javascript

---

CHANGELOG.md
docs/reference/organization/repository/branch-or-tag.md
docs/reference/organization/repository/environment.md
mkdocs.yml
otterdog/models/environment.py
otterdog/providers/github/rest/repo_client.py

feat: add support for tags in deployment policies within environments

---

CHANGELOG.md
otterdog/cli.py
otterdog/models/__init__.py
otterdog/models/repository.py
otterdog/models/secret.py
otterdog/models/webhook.py
otterdog/operations/apply.py
otterdog/operations/diff_operation.py
otterdog/operations/local_apply.py
otterdog/operations/local_plan.py
otterdog/operations/open_pull_request.py
otterdog/operations/plan.py
otterdog/operations/push_config.py
otterdog/webapp/tasks/apply_changes.py
otterdog/webapp/tasks/check_sync.py
otterdog/webapp/tasks/validate_pull_request.py

feat: add support for repo-filter parameter for planning operations

---

CHANGELOG.md
docker/docker-compose.base.yml
docker/docker-compose.dev.yml
docker/docker-compose.prod.yml
otterdog/app.py
otterdog/cache.py
otterdog/cli.py
otterdog/credentials/__init__.py
otterdog/providers/github/__init__.py
otterdog/providers/github/cache/__init__.py
otterdog/providers/github/cache/file.py
otterdog/providers/github/cache/ghproxy.py
otterdog/providers/github/cache/redis.py
otterdog/providers/github/graphql.py
otterdog/providers/github/rest/__init__.py
otterdog/providers/github/rest/requester.py
otterdog/webapp/__init__.py
otterdog/webapp/config.py
otterdog/webapp/utils.py

feat: Integrate and use ghproxy

---

CHANGELOG.md
otterdog/models/__init__.py
otterdog/models/repository.py
otterdog/models/secret.py
otterdog/models/webhook.py
otterdog/operations/apply.py

change: improve archiving of a repository

---

CHANGELOG.md
otterdog/app.py
otterdog/providers/github/rest/app_client.py
otterdog/webapp/blueprints/__init__.py
otterdog/webapp/db/models.py
otterdog/webapp/db/service.py
otterdog/webapp/internal/routes.py
otterdog/webapp/tasks/__init__.py
otterdog/webapp/tasks/fetch_blueprints.py
otterdog/webapp/utils.py

Improve update mechanism for new installations and check for blueprints

---

CHANGELOG.md
otterdog/providers/github/exception.py
otterdog/providers/github/rest/requester.py

Indicate missing oauth scopes if a request fails because of that

---

docs/contributing.md

The project has moved from GitLab to GitHub so update the links.

chore: Update GitLab links to GitHub

---

CHANGELOG.md
otterdog/models/team.py
otterdog/providers/github/__init__.py
otterdog/providers/github/rest/team_client.py

See https://github.com/orcwg/.eclipsefdn/pull/1

Fix updating teams with local-apply operation

---

.gitignore
Makefile
dev/dev-values-ts.yaml
dev/dev-values.yaml
dev/skaffold.yaml
docs/contributing.md

This PR introduces the initial automation setup for a more accessible and developer-friendly experience.  
It serves as a foundational seed to improve local development workflows.
- **Minikube + Skaffold Integration**
- Enables contributors to run the full development environment locally using Kubernetes.
- Supports ARM-based systems, ensuring compatibility across diverse development machines.
- **Helm-Based Deployment**
- Leverages existing Helm charts to deploy services into Minikube, promoting consistency with production deployments.
- **Live Code Reloads**
- Skaffold monitors source code changes and automatically rebuilds and redeploys images.
- Provides a lightweight end-to-end (E2E) testing loop, enhancing development feedback cycles.
- **GitHub Integration via Local OtterDog …

improve contributing and dev environment

---

CHANGELOG.md
otterdog/providers/github/rest/repo_client.py
tests/providers/github/rest/test_repo_client.py

This commit fixes the regression and adds UT
Closes #458

fix: regression for #423

---

otterdog/models/repository.py
tests/models/test_repository.py

Add helper function for squash merge commit message

refactor: add helper func for squash commit prop

---

CHANGELOG.md

added updates from last changes

chore: update changelog with last updates

---

CHANGELOG.md

Hi folks,
I'm proposing to release today version v1.1.0 as we added new features and other minor changes and updates.
cc @netomi, @mbarbero, @iliescuioana

release: prepare v1.1.0

---

CHANGELOG.md
otterdog/app.py

Use `exist_ok=True` in `os.makedirs()` calls to prevent `FileExistsError` when multiple workers attempt to create the same directories simultaneously.
This resolves crashes during webapp startup in multi-worker environments.
```log
[otterdog] Process SpawnProcess-1:
[otterdog] Traceback (most recent call last):
[otterdog] [2025-09-25 07:47:30.815  ] [10] [INFO] DEBUG         = True
[otterdog] [2025-09-25 07:47:31.014  ] [10] [INFO] Environment   = Debug
[otterdog]   File "/usr/local/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
[otterdog]     self.run()
[otterdog]   File "/usr/local/lib/python3.12/multiprocessing/process.py", line 108, in run
[otterdog]     self._target(*self._args, **self._kwargs)
[otterdog]   File …
```

fix: race condition on app startup creating dirs
