eclipse-csi/otterdog

CHANGELOG.md
DEPENDENCIES
otterdog/config.py
otterdog/operations/push_config.py
otterdog/providers/github/__init__.py
otterdog/providers/github/rest/content_client.py
poetry.lock
pyproject.toml

This fixes #228 .
Adds author information from local git config if present when using operation `push-config`.

feat: add author information when using operation push-config

---

CHANGELOG.md
otterdog/cli.py
otterdog/operations/fetch_config.py
otterdog/operations/local_apply.py
otterdog/providers/github/rest/commit_client.py
otterdog/webapp/db/service.py
otterdog/webapp/tasks/apply_changes.py
otterdog/webapp/tasks/check_sync.py

This fixes #257 .
Adds a new operation local-apply to apply all changes between two local configurations.
That is used in the ApplyChangesTask of the GitHub App to apply approved changes from a PR. The task will fetch the latest config that has been modified by the PR and the previous one, run the local-apply operation with these 2 configs.
That should avoid getting the current live configuration from GitHub, reducing the number of API calls and speeding up the applying. It is safe to do so as the check-sync task will ensure that the configuration is in sync.

feat: add new operation local-apply and use it for the ApplyChangesTask

---

README.md

Required by one of the dep packages in otterdog (gojsonnet). W/o go installed the call to `make init` will fail due to an inability to build the wheel for gojsonnet, blocking the script.

update: Mark go as a required bin for otterdog

---

.github/workflows/publish.yml

Reverts eclipse-csi/otterdog#316

Revert "chore(deps): bump pypa/gh-action-pypi-publish from 1.11.0 to 1.12.2"

---

.github/workflows/build.yml
README.md
poetry.lock
pyproject.toml

This PR adds support for tox to run tests for different python versions locally.
It also reinstates python 3.13 as supported version now that rjsonnet is used.

Add support for tox

---

CHANGELOG.md
otterdog/operations/apply.py
otterdog/utils.py
otterdog/webapp/tasks/apply_changes.py
otterdog/webapp/tasks/check_sync.py
otterdog/webapp/tasks/validate_pull_request.py

This fixes #318 .
Adds a `post-add-objects` hook for the default config.
Example output:
``` diff
! Warning: The following GitHub repos have been created:
!      - https://github.com/OtterdogTest/test-repo8
!    Committers will gain access to it once the sync script runs (~2h).
```

feat: add post-add-objects hook for apply operation

---

CHANGELOG.md
otterdog/providers/github/rest/org_client.py
otterdog/providers/github/rest/repo_client.py

fix: updating or deleting webhooks with wildcards via the local-apply operation

---

CHANGELOG.md
docs/reference/blueprints/append-configuration.md
mkdocs.yml
otterdog/webapp/blueprints/__init__.py
otterdog/webapp/blueprints/append_configuration.py
otterdog/webapp/blueprints/pin_workflow.py
otterdog/webapp/blueprints/required_file.py
otterdog/webapp/tasks/blueprints/__init__.py
otterdog/webapp/tasks/blueprints/append_configuration.py
otterdog/webapp/webhook/__init__.py
otterdog/webapp/webhook/github_models.py
poetry.lock
pyproject.toml
tests/webapp/blueprints/test_append_configuration.py

This adds an append_configuration blueprint that will check if a given condition that is evaluated against the current configuration of a the project / organization is true. If false, the given configuration snippet is added via a PR.
This allows to model blueprints like
- add a .github repo if it does not exist
- add an organization ruleset to prevent force pushes

feat: add append configuration blueprint

---

CHANGELOG.md
docs/reference/organization/index.md
docs/reference/organization/role.md
examples/template/otterdog-defaults.libsonnet
mkdocs.yml
otterdog/jsonnet.py
otterdog/models/github_organization.py
otterdog/models/organization_role.py
otterdog/models/organization_ruleset.py
otterdog/models/organization_settings.py
otterdog/models/repository.py
otterdog/models/role.py
otterdog/operations/__init__.py
otterdog/operations/diff_operation.py
otterdog/operations/import_configuration.py
otterdog/operations/install_app.py
otterdog/operations/local_apply.py
otterdog/operations/local_plan.py
otterdog/operations/show_default.py
otterdog/operations/show_live.py
otterdog/providers/github/__init__.py
otterdog/providers/github/rest/org_client.py
otterdog/resources/schemas/org-role.json
otterdog/resources/schemas/organization.json
otterdog/resources/schemas/role.json
otterdog/resources/schemas/settings.json
otterdog/webapp/db/service.py
otterdog/webapp/home/routes.py
tests/models/resources/test-org/test-org.jsonnet
tests/models/resources/test-org/vendor/test-defaults/test-defaults.libsonnet

This fixes #356 .
The PR introduces support for organization roles and replaces the logic wrt security manager settings.
These setting is deprecated and should be replaced with assigning the security_manager role to teams.
However this has the downside, that with the security manager role teams also have the permissions to alter security configurations for the organization. We would like to avoid that and only allow to configure that via otterdog itself. For that purpose we can define our own custom role that has the same permissions as the predefined security manager role but lacks permissions to alter the security configuration. That seems to be built in the predefined rule.
That is a clean workaround that improves the status quo as all security managers can update the security …

Add support for organization roles and rework security manager setting

---

docs/reference/organization/repository/status-check.md

After struggling multiple times with this I'd like to add a small note in the documentation to highlight the fact that the whitespaces in the ` / ` status check separator are not optional. Feel free to provide any additional feedback on how to make this more clear.

docs: add note about reusable workflows status check separator

---

.gitignore

Ignore otterdog config file `otterdog.json` to prevent developers/contributors from adding it while developing.

chore: ignore otterdog.json

---

Makefile

This speeds up subsequent `make init` calls.
It first checks if the dynamic versioning plugin is already installed and only then will run `poetry sync --only-root` to install the plugin.

Add explicit check if dynamic versioning plugin is installed

---

CHANGELOG.md
otterdog/models/organization_settings.py
otterdog/models/repository.py

This PR fixes 2 small bugs that you hit when importing the current OtterdogTest org:
- do not serialize inherited custom properties
- coerce the has_discussions property of a repo if its the source of organization discussions (that might be a change on GitHub side as this used to work)

Fix inconsistencies wrt import operation

---

Makefile

Call playwright using `python -m playwright` as
`poetry run playwright` doesn't appear to work on MacOSX.
py.test didn't work on my system and `pytest` has been the recommended way to invoke pytest since version 3.0 so update the Makefile to use that method.

fix: Adjust Makefile to work on MacOSX

---

otterdog/webapp/db/__init__.py
tests/webapp/db/test__init__.py

Refactor existing parser with helper `_parse` function using urlparse, fixing compatibility issues with k8s cluster deployments using svc.local URLs as an example.

fix: correct MongoDB URI parsing functionality

---

TESTING.md

The URL has a typo so clicking the link routes to an invalid URL.

docs: Fix typo in URL

---

.github/workflows/publish.yml

This might happen due to dynamic versioning and we should ignore these errors.
The whole idea of publishing to test pypi is to make sure the workflow works before doing a real release.

Skip existing versions when publishing to test.pypi.org

---

CHANGELOG.md

Prepare otterdog 1.0.3 release
- Dependencies updates for otterdog
- Minor development docs and build updates

Prepare otterdog 1.0.3

---

TESTING.md

In order to configure the permission "issue comment" we must grant the "Issues" permission first.

docs: Document issues permission

---

docker/docker-compose.base.yml

This does not appear to be a multiarch image so hardcode the platform to be linux/amd64 so that it does not fail when run on non-amd64 hardware.
> Error response from daemon: image with reference us-docker.pkg.dev/k8s-infra-prow/images/ghproxy:v20240923-efb534162 was found but its platform (linux/amd64) does not match the specified platform (linux/arm64)

fix: Set platform to linux/amd64 for ghproxy

---

TESTING.md

Explain that the GITHUB_WEBHOOK_VALIDATION_CONTEXT and GITHUB_WEBHOOK_SYNC_CONTEXT can be set to any string and will be used to as the name of the checks reported to GitHub Actions.
Would be better to have this detail in a more comprehensive doc as proposed by #434 but this should give those following TESTING.md some clarity.
Closes: #422

Add details on the 2 webhook contexts

---

CHANGELOG.md
otterdog/cli.py
otterdog/operations/apply.py
otterdog/operations/check_status.py
otterdog/operations/diff_operation.py
otterdog/operations/plan.py
otterdog/operations/validate.py
otterdog/providers/github/rest/org_client.py
otterdog/webapp/tasks/check_sync.py
otterdog/webapp/tasks/validate_pull_request.py

The output is in json format:
```
otterdog check-status A B C
[
{
"org_id": "A",
"validation_status": {
"is_valid": true,
"infos": 0,
"warnings": 0,
"errors": 0
},
"sync_status": {
"in_sync": true,
"additions": 0,
"changes": 0,
"deletions": 0
}
},
{
"org_id": "B",
"validation_status": {
"is_valid": false,
"infos": 0,
"warnings": 0,
"errors": 2
},
"sync_status": {
"in_sync": false,
"additions": 0,
"changes": 0,
"deletions": 0
}
},
{
"org_id": "C",
"validation_status": {
"is_valid": true,
"infos": 47,
"warnings": 0,
"errors": 0
},
"sync_status": {
"in_sync": false,
"additions": 0,
"changes": 1,
"deletions": 0
}
}
]
```

Add command to check the validation and sync status of orgs
